package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTaskName(java.lang.String taskName) {
		set("taskName", taskName);
		return (M)this;
	}
	
	public java.lang.String getTaskName() {
		return getStr("taskName");
	}

	public M setTaskImage(java.lang.String taskImage) {
		set("taskImage", taskImage);
		return (M)this;
	}
	
	public java.lang.String getTaskImage() {
		return getStr("taskImage");
	}

	public M setBasicPrice(java.lang.Integer basicPrice) {
		set("basicPrice", basicPrice);
		return (M)this;
	}
	
	public java.lang.Integer getBasicPrice() {
		return getInt("basicPrice");
	}

	public M setResultPrice(java.lang.Integer resultPrice) {
		set("resultPrice", resultPrice);
		return (M)this;
	}
	
	public java.lang.Integer getResultPrice() {
		return getInt("resultPrice");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setTotalPart(java.lang.Integer totalPart) {
		set("totalPart", totalPart);
		return (M)this;
	}
	
	public java.lang.Integer getTotalPart() {
		return getInt("totalPart");
	}

	public M setIsEnd(java.lang.Integer isEnd) {
		set("isEnd", isEnd);
		return (M)this;
	}
	
	public java.lang.Integer getIsEnd() {
		return getInt("isEnd");
	}

}
