package com.demo.common.model;

import com.demo.common.model.base.BaseInvitationCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvitationCode extends BaseInvitationCode<InvitationCode> {
	
}
